run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nolintlint
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
